/*
 * This source file was generated by the Gradle 'init' task
 */
package sourcecontrol;

public class SourceControl {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new SourceControl().getGreeting());
    }
}
